# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575ebe9b7e3d9e88035c687b453debd89eaca1e969a79359108137830ffc6981b22c53c6e3f09f301fd3dbf75f78b82e0c89a85c2d819af70109ca97a94c030b

test:
  secret_key_base: b8919b3f1e5221950b9609cb163ec4511d3a24705007e6d39f01a26d6db160aa9af8a9c8087af784ebe4e0e55ac40e5bdaa333a511a9b57dcfb7158b3f4ec64a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
